name: Package Release
on:
  push:
    branches:
      - main

jobs:
  package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build and package
        run: |
          pyinstaller --noconfirm --onefile --windowed StartUI.py
          cp webuiGUI.py dist/  # Copy webuiGUI.py to the dist directory

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-binary-v1.1
          path: dist
