name: Package Release
on:
  push:
    paths:
      - .github/workflows/**
  workflow_dispatch:

jobs:
  package_on_ubuntu:
    runs-on: ubuntu-selfhosted
    steps:
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upgrade Pip
        run: python -m pip install --upgrade pip
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install nuitka

      - name: Build and package
        run: python3 -m nuitka StartUI.py --onefile --enable-plugin=pyqt5 --product-version=1.6.0 --disable-console --include-data-files=webuiGUI.py=webuiGUI.py --output-dir=./dist --noinclude-pytest-mode=nofollow --noinclude-setuptools-mode=nofollow

      - name: remove build folders
        run: |
          rm -rf dist/StartUI.build
          rm -rf dist/StartUI.dist
          rm -rf dist/StartUI.onefile-build

      - name: Executive permission
        run: |
          chmod +x dist/StartUI

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ubuntu-binary-v1.6
          path: dist

  package_on_windows:
    runs-on: windows-selfhosted
    steps:
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upgrade Pip
        run: python -m pip install --upgrade pip
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install nuitka

      - name: Build and package
        run: nuitka StartUI.py --onefile --enable-plugin=pyqt5 --product-version=1.6.0 --disable-console --include-data-files=webuiGUI.py=webuiGUI.py --output-dir=./dist --noinclude-pytest-mode=nofollow --noinclude-setuptools-mode=nofollow

      - name: remove build folders
        run: |
         Remove-Item -Recurse -Force ./dist/StartUI.build
         Remove-Item -Recurse -Force ./dist/StartUI.dist
         Remove-Item -Recurse -Force ./dist/StartUI.onefile-build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-binary-v1.6
          path: dist
